# config.py
MAPEAMENTO_COLUNAS = {
    "#": "Chave",
    "SUMÁRIO": "Resumo",
    "DESCRIÇÃO": "Descrição",
    "STATUS": "Situação",
    "TIPO CHAMADO": "Tipo de Item",
    "PRIORIDADE": "Prioridade",
    "REABERTO": "Reaberto",
    "DATA ABERTURA": "Criado",
    "USUÁRIO AFETADO": "Usuário afetado",
    "DATA RESOLUÇÃO": "Resolvido",
    "DATA FECHAMENTO": "Data do Fechamento",
    "RELATADO POR": "Solicitante",
    "GRUPO RESPONSÁVEL": "Grupo solucionador",
    "RESPONSÁVEL": "Responsável",
    "TIPO DE FECHAMENTO": "Tipo de fechamento",
    "CATEGORIA": "Categoria",
    "PROJETO RELACIONADO": "Projeto relacionado",
    "ORIGINADO POR": "Canal de Acionamento",
    "TEMPO TOTAL DA ATIVIDADE": "Tempo de Solução",
    "TEMPO DE RESPOSTA": "Tempo até a primeira resposta",
    "ITEM DE CONFIGURAÇÃO": "IC - 1",
    "DATA PREV. TER. ANÁLISE": "Analise",
    "DATA PREV. INI. HOMOLOGAÇAÕ": "Homologação",
    "DATA PREV. TER. DESENVOLVIMENTO": "Desenvolvimento",
    "DATA PREV. INI. PRODUÇÃO": "Produção",
}

COLUNAS_RELATORIO = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "AA",
    "AB",
    "AC",
    "AD",
    "AE",
    "AF",
    "AG",
    "AH",
    "AI",
    "AJ",
    "AK",
    "AL",
    "AM",
    "AN",
    "AO",
    "AP",
    "AQ",
    "AR",
    "AS",
    "AT",
    "AU",
    "AV",
    "AW",
    "AX",
    "AY",
    "AZ",
    "BA",
    "BB",
    "BC",
    "BD",
]
